apiVersion: v2
name: kubeml
version: 0.1.3
description: KubeML is a Serverless Platform to Train Neural Networks on Kubernetes
keywords:
  - serverless
  - deep learning
maintainers:
  - name: Diego Albo
    email: diego.albo.martinez@gmail.com
  - name: Stefan Petrescu
    email: hello.spetrescu@gmail.com
appVersion: 0.1.3

